server:
  port: 9800

spring:
  datasource:
    url: jdbc:log4jdbc:h2:tcp://localhost/~/spring-security
    username: admin
    password: admin
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  data:
    redis:
      host: localhost
      port: 6379

token:
  access-token-expired-time: 1m
  refresh-token-cookie-secure: false
  refresh-token-cookie-key: sbo-refresh
  refresh-token-expired-time: 10m

logging:
  level:
    com.practice.securitybeginner: DEBUG
