spring:
  profiles:
    active: local
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

mybatis:
  mapper-locations: mybatis/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.practice.securitybeginner.domain

token:
  secret-key: Jzz4p/T4MtBbFsk/d1RyilDTxmElYnPQdlP1YWNrEDo=
  re-issue-url: /api/auth/refresh
