-- PUBLIC.TB_ROLE definition

-- Drop table

-- DROP TABLE PUBLIC.TB_ROLE;

CREATE TABLE PUBLIC.TB_ROLE (
	ROLE_ID INTEGER,
	ROLE_NAME CHARACTER VARYING(100)
);

INSERT INTO PUBLIC.TB_ROLE
(ROLE_ID, ROLE_NAME)
VALUES(1000, 'ADMIN');
INSERT INTO PUBLIC.TB_ROLE
(ROLE_ID, ROLE_NAME)
VALUES(1001, 'MANAGER');
INSERT INTO PUBLIC.TB_ROLE
(ROLE_ID, ROLE_NAME)
VALUES(1002, 'USER');
INSERT INTO PUBLIC.TB_ROLE
(ROLE_ID, ROLE_NAME)
VALUES(1003, 'GUEST');