-- PUBLIC.TB_USER_ROLE definition

-- Drop table

-- DROP TABLE PUBLIC.TB_USER_ROLE;

CREATE TABLE PUBLIC.TB_USER_ROLE (
	USER_ID CHARACTER VARYING(255),
	ROLE_ID INTEGER
);

INSERT INTO PUBLIC.TB_USER_ROLE
(USER_ID, ROLE_ID)
VALUES('admin@solbione.com', 1002);
INSERT INTO PUBLIC.TB_USER_ROLE
(USER_ID, ROLE_ID)
VALUES('admin@solbione.com', 1000);
INSERT INTO PUBLIC.TB_USER_ROLE
(USER_ID, ROLE_ID)
VALUES('temp@naver.com', 1002);
INSERT INTO PUBLIC.TB_USER_ROLE
(USER_ID, ROLE_ID)
VALUES('temp@naver.com', 1000);
INSERT INTO PUBLIC.TB_USER_ROLE
(USER_ID, ROLE_ID)
VALUES('temp2@naver.com', 1002);
INSERT INTO PUBLIC.TB_USER_ROLE
(USER_ID, ROLE_ID)
VALUES('temp2@naver.com', 1000);